---
filled_verbs:
rename_maps:
  tweets:
    id: tweet_id
    text: text_orig
    author_id: user_id
    entities.mentions: mentions
    geo.place_id: tweet_place_id
  users:
    id: user_id
    location: user_location
  places:
    id: place_id
    full_name: location_full_name
