name: que_drop
channels: 
  - conda-forge
  - defaults
dependencies:
  - requests
  - yaml
  - python=3.10
  - notebook
  - numpy
  - unidecode
  - scipy
  - matplotlib
  - pandas
  - emoji
  - numexpr
  - libblas=*=*mkl
  - regex
  - spacy
  - cupy
  - spacy-transformers
  - python-decouple
  - pip
  - pip:
    - spacy-lookups-data
    - ipyparams
